### ISSUE TITLE
CreeperOverhaul API evaluation fails on 1.19.2

### ISSUE THREAD

**Issue by Mirsario** [Crendgrim/DynamicCrosshairCompat#20]
# Issue
Hi. Just notifying that, currently, when using latest versions of DynamicCrosshair+Compat and CreeperOverhaul ___that are available for 1.19.2 MC___, this mod may silently print
`java.lang.NoSuchMethodError: 'boolean tech.thatgravyboat.creeperoverhaul.common.entity.base.CreeperType.shearable()'`
exceptions.

**Full stacktrace:** [DynamicCrosshairCompat-CreeperOverhaul.log](https://github.com/Crendgrim/DynamicCrosshairCompat/files/11954519/DynamicCrosshairCompat-CreeperOverhaul.log)

**DynamicCrosshair version:** `v5.6.2`
**DynamicCrosshairCompat version:** `v3.3.2`
**CreeperOverhaul version:** `v2.0.9`

I'm guessing this is because `v3.0`+ of CO were targeted, but releases of that major are 1.20+ only.

# Misc
It'd be nice if there was a config for the compat mod with boolean toggles per supported mod, so that integrations with them could be skipped when borked.

Excellent base mod by the way, thank you for making it.

**Comment by Crendgrim** [comment]
Thank you for the report!


> It'd be nice if there was a config for the compat mod with boolean toggles per supported mod, so that integrations with them could be skipped when borked.

This is also a good idea. I've also considered auto-disabling integrations that have failed. My problem has always been that I don't know how much I should do to prevent bugs, because I don't know whether I'll get any reports then. When it still hard-crashed I imagine I got more reports than now where there's only log spam, and I'm suspecting I won't get many reports at all when it just silently doesn't work. :/ Sending a chat message feels too intrusive, just silently ignoring any errors too oblique.

**Comment by Mirsario** [comment]
You could show warnings in the config GUI, though I guess few people will still be interested in opening it. I think that chat messages are fine if there's an option to turn them off, some mods don't have that and now those cases are definitely unbearable.

**Comment by Crendgrim** [comment]
I'm only worried about misconfigured modpacks, really. I find it very annoying to start a modpack and be spammed by several different mods in chat. I'll have to think about it more.

In the meantime, I pushed DCC 3.3.3 that should fix the original issue here.

**Comment by Mirsario** [comment]
That helped, thanks. And the cacti creepers get the shearing crosshair correctly.
